baseurl = "https://phoenix-engine.github.io/"
languageCode = "en-us"
title = "Phoenix Engine"
theme = "hugo-xmin"
googleAnalytics = "UA-125715664-1"
disqusShortname = "phoenix-engine"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "The Phoenix Engine site is built in Hugo, using [XMin](https://xmin.yihui.name/)."
    footer = "&copy; Bodie Solomon 2018 | [bodie@synapsegarden.net](mailto:bodie@synapsegarden.net) | [https://github.com/phoenix-engine](https://github.com/phoenix-engine)"
